services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=jva_montagens'
      - 'POSTGRES_PASSWORD=250103'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432' # <--- Porta Externa : Porta Interna
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: